### ISSUE TITLE
Disable nav link when it's the current page

### ISSUE THREAD

**Issue by schneiderfelipe** [getcuia/getcuia.github.io#5]

**Comment by NickRTR** [comment]
Should it be grayed out or removed? Or should just nothing happen when you click it?

**Comment by schneiderfelipe** [comment]
Hi @NickRTR I'm thinking about leaving it gray and disable the link behaviour.

**Comment by NickRTR** [comment]
Ok, I can do that, but the pages where the links don't work, because the pages aren't created, right?

**Comment by schneiderfelipe** [comment]
Hey, thanks! I just realized that most links are broken. Can you help me out on that one too?

**Comment by NickRTR** [comment]
In my dev Server the links are working.
